-- Task C: Hub Coverage & Store Network Analysis
-- SQL queries for hub metrics calculation
-- Author: Ivan Zamurenko
-- Date: October 30, 2025


-- ==========================================
-- Query 1: Stores per Hub
-- ==========================================
-- Calculate the number of stores associated with each hub

SELECT 
    h.hub_id,
    h.hub_name,
    h.hub_city,
    h.hub_state,
    COUNT(DISTINCT s.store_id) AS store_count
FROM hubs h
LEFT JOIN stores s ON h.hub_id = s.hub_id
GROUP BY h.hub_id, h.hub_name, h.hub_city, h.hub_state
ORDER BY store_count DESC;


-- ==========================================
-- Query 2: Revenue per Hub
-- ==========================================
-- Calculate total revenue generated by each hub
-- (via stores connected to the hub)

WITH hub_orders AS (
    SELECT 
        s.hub_id,
        o.order_id,
        o.store_id
    FROM orders o
    JOIN stores s ON o.store_id = s.store_id
),
hub_revenue AS (
    SELECT 
        ho.hub_id,
        COUNT(DISTINCT ho.order_id) AS order_count,
        SUM(p.payment_amount) AS total_revenue
    FROM hub_orders ho
    JOIN payments p ON ho.order_id = p.payment_order_id
    GROUP BY ho.hub_id
)
SELECT 
    h.hub_id,
    h.hub_name,
    h.hub_city,
    h.hub_state,
    COALESCE(hr.order_count, 0) AS order_count,
    COALESCE(hr.total_revenue, 0) AS total_revenue
FROM hubs h
LEFT JOIN hub_revenue hr ON h.hub_id = hr.hub_id
ORDER BY total_revenue DESC;


-- ==========================================
-- Query 3: Comprehensive Hub Metrics
-- ==========================================
-- Combine stores, orders, and revenue in one query

WITH stores_per_hub AS (
    SELECT 
        hub_id,
        COUNT(DISTINCT store_id) AS store_count
    FROM stores
    GROUP BY hub_id
),
hub_orders AS (
    SELECT 
        s.hub_id,
        o.order_id,
        o.store_id
    FROM orders o
    JOIN stores s ON o.store_id = s.store_id
),
hub_revenue AS (
    SELECT 
        ho.hub_id,
        COUNT(DISTINCT ho.order_id) AS order_count,
        SUM(p.payment_amount) AS total_revenue
    FROM hub_orders ho
    JOIN payments p ON ho.order_id = p.payment_order_id
    GROUP BY ho.hub_id
)
SELECT 
    h.hub_id,
    h.hub_name,
    h.hub_city,
    h.hub_state,
    COALESCE(sph.store_count, 0) AS store_count,
    COALESCE(hr.order_count, 0) AS order_count,
    COALESCE(hr.total_revenue, 0) AS total_revenue,
    CASE 
        WHEN COALESCE(sph.store_count, 0) > 0 
        THEN ROUND((COALESCE(hr.total_revenue, 0) / sph.store_count), 2)
        ELSE 0 
    END AS revenue_per_store
FROM hubs h
LEFT JOIN stores_per_hub sph ON h.hub_id = sph.hub_id
LEFT JOIN hub_revenue hr ON h.hub_id = hr.hub_id
ORDER BY total_revenue DESC;


-- ==========================================
-- Query 4: High-Potential Hubs
-- ==========================================
-- Identify hubs with many stores but low revenue
-- (potential for optimization/growth)

WITH hub_metrics AS (
    SELECT 
        h.hub_id,
        h.hub_name,
        h.hub_city,
        h.hub_state,
        COUNT(DISTINCT s.store_id) AS store_count,
        COUNT(DISTINCT o.order_id) AS order_count,
        COALESCE(SUM(p.payment_amount), 0) AS total_revenue
    FROM hubs h
    LEFT JOIN stores s ON h.hub_id = s.hub_id
    LEFT JOIN orders o ON s.store_id = o.store_id
    LEFT JOIN payments p ON o.order_id = p.payment_order_id
    GROUP BY h.hub_id, h.hub_name, h.hub_city, h.hub_state
),
quartiles AS (
    SELECT 
        PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY store_count) AS store_q75,
        PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY total_revenue) AS revenue_q25
    FROM hub_metrics
)
SELECT 
    hm.hub_id,
    hm.hub_name,
    hm.hub_city,
    hm.hub_state,
    hm.store_count,
    hm.order_count,
    hm.total_revenue,
    (hm.total_revenue / NULLIF(hm.store_count, 0)) AS revenue_per_store
FROM hub_metrics hm
CROSS JOIN quartiles q
WHERE hm.store_count >= q.store_q75
    AND hm.total_revenue <= q.revenue_q25
ORDER BY hm.store_count DESC;


-- ==========================================
-- Query 5: Consolidation Targets
-- ==========================================
-- Identify hubs with few stores and low revenue
-- (candidates for consolidation or closure)

WITH hub_metrics AS (
    SELECT 
        h.hub_id,
        h.hub_name,
        h.hub_city,
        h.hub_state,
        COUNT(DISTINCT s.store_id) AS store_count,
        COUNT(DISTINCT o.order_id) AS order_count,
        COALESCE(SUM(p.payment_amount), 0) AS total_revenue
    FROM hubs h
    LEFT JOIN stores s ON h.hub_id = s.hub_id
    LEFT JOIN orders o ON s.store_id = o.store_id
    LEFT JOIN payments p ON o.order_id = p.payment_order_id
    GROUP BY h.hub_id, h.hub_name, h.hub_city, h.hub_state
),
quartiles AS (
    SELECT 
        PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY store_count) AS store_q75,
        PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY total_revenue) AS revenue_q25
    FROM hub_metrics
)
SELECT 
    hm.hub_id,
    hm.hub_name,
    hm.hub_city,
    hm.hub_state,
    hm.store_count,
    hm.order_count,
    hm.total_revenue,
    (hm.total_revenue / NULLIF(hm.store_count, 0)) AS revenue_per_store
FROM hub_metrics hm
CROSS JOIN quartiles q
WHERE hm.store_count < q.store_q75
  AND hm.total_revenue <= q.revenue_q25
ORDER BY hm.total_revenue ASC;


-- ==========================================
-- Query 6: Top Performing Hubs
-- ==========================================
-- Identify hubs with high revenue per store
-- (operational benchmarks)

WITH hub_metrics AS (
    SELECT 
        h.hub_id,
        h.hub_name,
        h.hub_city,
        h.hub_state,
        COUNT(DISTINCT s.store_id) AS store_count,
        COUNT(DISTINCT o.order_id) AS order_count,
        COALESCE(SUM(p.payment_amount), 0) AS total_revenue,
        (COALESCE(SUM(p.payment_amount), 0) / NULLIF(COUNT(DISTINCT s.store_id), 0)) AS revenue_per_store
    FROM hubs h
    LEFT JOIN stores s ON h.hub_id = s.hub_id
    LEFT JOIN orders o ON s.store_id = o.store_id
    LEFT JOIN payments p ON o.order_id = p.payment_order_id
    GROUP BY h.hub_id, h.hub_name, h.hub_city, h.hub_state
),
quartiles AS (
    SELECT 
        PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY revenue_per_store) AS revenue_per_store_q75
    FROM hub_metrics
)
SELECT 
    hm.hub_id,
    hm.hub_name,
    hm.hub_city,
    hm.hub_state,
    hm.store_count,
    hm.order_count,
    hm.total_revenue,
    hm.revenue_per_store
FROM hub_metrics hm
CROSS JOIN quartiles q
WHERE hm.revenue_per_store >= q.revenue_per_store_q75
ORDER BY hm.revenue_per_store DESC;


-- ==========================================
-- Query 7: Hub State Summary
-- ==========================================
-- Aggregate hub metrics by state for regional analysis

SELECT 
    h.hub_state,
    COUNT(DISTINCT h.hub_id) AS hub_count,
    COUNT(DISTINCT s.store_id) AS store_count,
    COUNT(DISTINCT o.order_id) AS order_count,
    COALESCE(SUM(p.payment_amount), 0) AS total_revenue,
    ROUND(AVG(COUNT(DISTINCT s.store_id)) OVER (PARTITION BY h.hub_state), 2) AS avg_stores_per_hub,
    ROUND(COALESCE(SUM(p.payment_amount), 0) / NULLIF(COUNT(DISTINCT h.hub_id), 0), 2) AS avg_revenue_per_hub
FROM hubs h
LEFT JOIN stores s ON h.hub_id = s.hub_id
LEFT JOIN orders o ON s.store_id = o.store_id
LEFT JOIN payments p ON o.order_id = p.payment_order_id
GROUP BY h.hub_state
ORDER BY total_revenue DESC;
